### ISSUE TITLE
Visual issues with Portals

### ISSUE THREAD

**Issue by Soundtoxin** [iChun/IssueTracker-PortalGun#37] opened 2015-04-13 00:23 UTC
I'm running Debian Jessie GNU/Linux amd64 architecture with multiarch enabled. Latest proprietary Oracle Java 8. I am playing multiplayer on my own server.

All of my portals show up with black borders instead of the colors assigned to me.
Image: http://a.pomf.se/zungjw.png
I've also had one or both of the two rings on my crosshair become empty without my portals actually closing. If I shoot a new one, that one will light up, but the second one will not. The portals still link. I have no image of this at the moment.

Modlist: http://sprunge.us/bFPJ
fml-client-latest.log: http://sprunge.us/RAGQ

**Comment by iChun** [comment] 2015-04-13 10:41
As you should know, PortalGun for 1.7.10 is unsupported. I won't be fixing any minor (this is considered a minor issue IMO) issues that come up with the mod, sorry.

**Closed as completed by iChun** 2015-04-13 10:41 UTC

**Comment by Soundtoxin** [comment] 2015-04-13 15:31
This issue is not minor. You can't tell your two portals apart and you could end up moving/closing the wrong portal. Are you going to call all issues minor? I also crash when grabbing blocks with the portal gun (but not entities) and the portal gun recipe doesn't show in NEI at all. Maybe those are too minor to fix as well.

**Comment by iChun** [comment] 2015-04-13 15:40
In retrospect, yes, this is a minor issue. I've already fixed the block grabbing crash (now that I would consider important/major), so you can get beta-3 to fix that. The recipe not showing up is also a relatively minor issue.

**Comment by iChun** [comment] 2015-04-13 16:09
It's fixed in beta 4. Your issue turns out to be due to something that was indeed (imo) pretty major so I had to get it fixed nevertheless. 

Now that it's fixed, again, PG 1.7.10 is supposed to be an UNSUPPORTED build of the mod. Stop bothering me to fix stuff when I said I'm not going to.

**Comment by iChun** [comment] 2015-04-13 16:10
And don't get snappy at me when I say the issue is minor.

**Comment by Soundtoxin** [comment] 2015-04-13 19:43
Thanks for letting me know of some of the fixes.

Tone does not carry over text and I believe you are in the wrong for assuming I was getting snappy with you. I'm not offended, though. I realize that this mod in general (at least on 1.7.10) is a weird subject with you.

**Comment by iChun** [comment] 2015-04-13 19:45
"This issue is not minor. ... Are you going to call all issues minor?" - Sounds snappy enough even without tone.
